name: 'Auto-assign author'

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.1.0
        with:
          repo-token: "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"
